version: '2.4'

services:
  web:
    build: .
    env_file:
      - ./docker_env.env
      - ./config/env_vars/testing_env.env
      - ./config/env_vars/db/testing_db.env
    volumes:
      - .:/web
    links:
      - db:db
    expose:
      - "9001"
    command:
      /bin/bash -c "pip install -r requirements_dev.txt; invoke run_it"

  db:
    image: postgres:9.6
    env_file:
      - ./config/env_vars/db/testing_db.env
    command: postgres

  sphinx:
    image: atomcream/sphinx
    expose:
      - 8001
    volumes:
      - .:/docs
    command:
      /bin/bash -c "pip install sphinx-autobuild recommonmark; sphinx-autobuild docs/source docs/build -H 0.0.0.0 --poll -p 8001"

  nginx-proxy:
    image: jwilder/nginx-proxy
    links:
      - web:web
    depends_on:
      - web
    volumes:
      - .:/web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/vhost.d:/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
    volumes_from:
      - web

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
