# Generated by Django 3.0 on 2020-01-20 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=250, verbose_name=' id of video in the source')),
                ('name', models.CharField(max_length=250, verbose_name='name of the video')),
                ('source_type', models.CharField(choices=[('Google Drive', 'Gdrive type'), ('Google Photos', 'Gphotos type')], max_length=250, verbose_name='source of the file')),
                ('youtube_id', models.CharField(blank=True, max_length=250, verbose_name='id of youtube uploaded video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting to upload'), ('download', 'Download'), ('uploading', 'In progress of uploading'), ('errors', 'Error message'), ('success', 'Successfully Uploaded')], default='waiting', max_length=50)),
                ('error_message_video', models.TextField(blank=True)),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vdrive.Processing')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processings', to='vdrive.Video')),
            ],
        ),
    ]
