# Generated by Django 3.0 on 2020-01-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0007_videoprocessing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoprocessing',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='videoprocessing',
            name='progress',
            field=models.IntegerField(null=True, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='videoprocessing',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting to upload'), ('download', 'Download'), ('uploading', 'In progress of uploading'), ('errors', 'Error message'), ('success', 'Successfully Uploaded')], default='waiting', max_length=10),
        ),
    ]
