# Generated by Django 3.0 on 2020-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0011_auto_20200116_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processing',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(default=0, verbose_name='File size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('waiting on drive', 'Waiting to upload'), ('deleted', 'Successfully deleted')], default='waiting on drive', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(default=0, max_length=250, verbose_name='thumbnail of the video'),
            preserve_default=False,
        ),
    ]
