# Generated by Django 3.0 on 2020-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0012_auto_20200127_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(verbose_name='thumbnail of the video'),
        ),
    ]
