# Generated by Django 3.0 on 2020-01-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0013_auto_20200128_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(max_length=1000, verbose_name='thumbnail of the video'),
        ),
    ]
