# Generated by Django 3.0 on 2020-01-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0014_auto_20200128_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.IntegerField(null=True, verbose_name='File size'),
        ),
    ]
